cache:
  directories:
  - $HOME/.cache/pre-commit

stages:
  - linting
  - test
  - deploy

language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "pypy3"

# config for test stage
install:
  - pip install -r requirements-test.txt
  - pip install tox-travis
script: tox

# configure additional linting stage
jobs:
  include:
    - stage: linting
      python: "3.7" # limit to single run, using python 3.7
      install:
        - pip install -r requirements-dev.txt
      script:
        - pyenv global 3.7.1 # Make Python available to pre-commit
        - pre-commit run --all-files
